# Generated by Django 4.1 on 2023-03-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_shopproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
