# Generated by Django 4.1 on 2023-03-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_shopproduct_last_update_shopproduct_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopproduct',
            old_name='last_update',
            new_name='last_modify',
        ),
    ]
