name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10, ]

    steps:
    - name: Install Dependencies
      run: |
        sudo apt install python3-testresources
        python -m pip install --upgrade pip
    - name: Install Poetry
      run: |
        python -m pip install poetry
        poetry install
        COPY ./poetry.lock ./ebs-catalog/
        COPY ./pyproject.toml ./ebs-catalog/
    - name: Run Tests
      run: |
        python manage.py test
