name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10, ]

    steps:
    - name: Install Dependencies
      run: |
        sudo apt install python3-testresources
        python -m pip install --upgrade pip
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Install libraries by poetry
      run: |
        poetry install --no-interaction
    - name: Run Tests
      run: |
        python manage.py test
